######################################################################
# Automatically generated by qmake (3.0) Fri Oct 6 13:25:55 2017
######################################################################

TEMPLATE = app
TARGET = applied_hw2_3
INCLUDEPATH += .
CONFIG += c++11
# Input
HEADERS += library.h
SOURCES += library.cpp libraryClient.cpp
